Add onchain models
charmverse/core pull request #399
Opened 2024-12-18 14:13 UTC by motechFR

### WHAT

### WHY

2024-12-18 22:00 UTC, mattcasey commented on src/prisma/schema.prisma
> +  scoutedNFTs                         ScoutNFT[]
We've been using "Nft" in most places, i think we should stay consistent

2024-12-18 22:01 UTC, mattcasey commented on src/prisma/schema.prisma
> +  onchain_gems_payout
why do we need a new gems_payout?

2024-12-18 22:07 UTC, mattcasey commented on src/prisma/schema.prisma
> +  walletAddress String
this should have a foreign key relationship to our ScoutWallet collection

2024-12-18 22:08 UTC, mattcasey commented on src/prisma/schema.prisma
> +  scoutId      String     @db.Uuid
this needs to connect to a ScoutWallet and not a scout directly

2024-12-18 22:08 UTC, mattcasey commented on src/prisma/schema.prisma
> +  sender        Scout?              @relation(fields: [senderId], references: [id], onDelete: Cascade, name: "tokenReceiptSender")
replace receipitnId/senderId with recipientWallet and senderWallet and connect them to ScoutWallet

2024-12-18 22:09 UTC, mattcasey requested changes
see comments

2024-12-18 22:11 UTC, mattcasey commented on src/prisma/schema.prisma
> +  claimedAt     DateTime?
might be good to add a transactionhash to show where it was claimed?

2024-12-20 10:58 UTC, motechFR commented
Thanks @mattcasey I've addressed all the feedback raised

2024-12-20 17:59 UTC, mattcasey approved these changes

2024-12-21 05:33 UTC, merged